services:
  database:
    image: mysql:latest
    container_name: "MySQL"
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      - MYSQL_DATABASE=portotech
      - MYSQL_USER=portotech
      - MYSQL_PASSWORD=portotech*2022
      - MYSQL_ROOT_PASSWORD=portotech*root*2022
    volumes:
      - mysql-storage-database:/var/lib/mysql

volumes:
  mysql-storage-database:
